In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import numpy as np
import pandas as pd
from sklearn.metrics import ndcg_score
from sklearn.model_selection import KFold
from itertools import chain
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

drive = 'gdrive/My Drive/TUBES_RECSYS/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


## **Collaborative Filtering using Matrix Factorization**

In [ ]:
# get ratings dataset
df_rating = pd.read_csv(drive + 'ratings.csv', sep=',')

# get movies dataset
df_movies = pd.read_csv(drive + 'movies.csv', sep=',')

In [ ]:
# display first 5 rows of rating dataset
df_rating.head(5)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
# display first 5 rows of movie dataset
df_movies.head(5)

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [ ]:
dataset_rating = df_rating
dataset_movies = df_movies

In [ ]:
# locate features and label for rating prediction
X = df_rating.iloc[:,[0,1]].values
y = df_rating.iloc[:,2].values

In [ ]:
"""
Input:
    U     : a set of users
    D     : a set of items
    R     : a matrix of dimension |U| x |D| that contains all users ratings towards a movie
    P     : an initial matrix of association between users and features with dimension |U| x K
    Q     : an initial matrix of association between items and features with dimension |D| x K
    K     : the number of latent features
    steps : the maximum number of steps to perform the optimization
    alpha : the learning rate
    beta  : the regularization parameter
@OUTPUT:
    the final matrices P and Q
"""

def matrix_factorization(R, P, Q, K, steps=6, alpha=0.0002, beta=0.02):
    Q = Q.T # transpose matrix Q
    
    for step in range(steps):
      for i in range(len(R)):
          for j in range(len(R[i])):
              if R[i][j] > 0: # only minimise errors of the observed user-item pairs
                  eij = R[i][j] - np.dot(P[i,:],Q[:,j]) # count error between real rating and estimated rating
                  for k in range(K): 
                      P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k]) # set update rules for P
                      Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j]) # set update rules for Q
      eR = np.dot(P,Q)
      e = 0
      for i in range(len(R)):
          for j in range(len(R[i])):
              if R[i][j] > 0:
                  e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2) # check the overall error 
                  for k in range(K):
                      e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) ) # add beta to avoid overfitting
      if e < 0.001:
          break
    return P, Q.T

In [ ]:
cv = KFold(n_splits=5, random_state=42, shuffle=True) # do cross-validation for 5 folds

df_user_items_pred = [] # initialize array that stores all dataframe of user and items prediction
score = [] # initialize NDCG score of test set

for train_index, test_index in cv.split(X):
    
    df_rating = dataset_rating
    
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index] # split into data train and data test
    real_val = y_test # save real rating of data test
    
    for i in range(len(test_index)):
        df_rating['rating'].iloc[test_index[i]] = 0 # mask data test result
    
    df_rating = df_rating.pivot(index='userId', columns='movieId', values='rating') # change dataframe to matrix of user and item (movie)
    df_rating = df_rating.fillna(0) # fill unrated movie's ratings with 0
    
    R = df_rating.to_numpy() 

    U = len(R) # intialize user latent features matrix
    D = len(R[0]) # initialize item latent features matrix
    K = 4 # set number of latent features

    P = np.random.rand(U,K) # initialize user latent features matrix with random values
    Q = np.random.rand(D,K) # initialize item latent features matrix with random values

    print("The Original Matrix")
    print(R)

    user_latent_features , item_latent_features  = matrix_factorization(R, P, Q, K)

    user_items_matrix = np.dot(user_latent_features, item_latent_features.T)
    print("\nThe Approximation matrix by MF")
    print(user_items_matrix)
    
    df_user_items =  pd.DataFrame(user_items_matrix, columns = df_rating.columns, index = df_rating.index) # set user items matrix as dataframe
    df_user_items_pred.append(df_user_items)
    
    predicted = [] # initialize empty list for predicted data test
    for i in range(len(X_test)):
        predicted.append(df_user_items.loc[X_test[i][0]][X_test[i][1]]) # get rating prediction of data test
    
    predicted = np.asarray([predicted]) 
    real_val = np.asarray([real_val])
    score.append(ndcg_score(real_val,predicted))  # evaluate NDCG score of data test prediction

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


The Original Matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]

The Approximation matrix by MF
[[3.93355118 3.51816958 2.90023802 ... 0.99344018 2.43608675 3.17497707]
 [2.8828714  2.44792476 2.00889575 ... 0.78666753 1.87176033 2.31429061]
 [1.99544556 1.55540968 1.47072015 ... 0.62817827 1.41822956 1.5639089 ]
 ...
 [4.52438748 3.68143995 2.82638576 ... 1.08180049 2.80391971 3.46119549]
 [2.95641747 2.33261766 1.9543789  ... 0.79679814 1.94682175 2.26764897]
 [5.31652507 4.61448665 3.81508727 ... 1.42735118 3.40872205 4.29181511]]


/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


The Original Matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 0.  0.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]

The Approximation matrix by MF
[[2.90838362 3.38804026 2.79416413 ... 1.43767089 1.51395786 2.23478706]
 [2.07891206 2.47430811 2.32896863 ... 0.89271945 1.3505083  1.31925064]
 [1.97129672 2.26062258 1.74708625 ... 1.09909826 0.87998249 1.65577926]
 ...
 [3.26986107 3.81796879 3.27127419 ... 1.61038079 1.78262261 2.42874411]
 [1.27565305 1.52113159 1.1067211  ... 0.61183842 0.66860017 0.87628543]
 [4.17598492 4.93719272 3.87484682 ... 2.21749363 2.22133854 2.84023249]]


/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


The Original Matrix
[[0.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 0.  0.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]

The Approximation matrix by MF
[[2.7505596  1.73402065 1.53518037 ... 0.83624608 1.4744098  1.93863167]
 [1.63557902 0.98530107 1.26226059 ... 0.49310456 0.93334164 1.3602988 ]
 [1.90715374 1.14321729 1.05758142 ... 0.3089623  0.9267034  1.17832693]
 ...
 [3.50640733 2.72647922 1.82755835 ... 0.69916372 1.77648114 2.10402361]
 [2.03859539 1.53904955 0.79607634 ... 0.21946564 0.9202223  0.95616055]
 [4.63295717 3.40009618 2.4294215  ... 1.02640546 2.36763563 2.87719813]]


/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


The Original Matrix
[[0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]]

The Approximation matrix by MF
[[1.8730311  2.2547664  2.29338119 ... 2.03164997 1.81140997 1.10087956]
 [1.08763028 1.42911902 1.55648582 ... 1.3507249  0.94646333 0.81189635]
 [1.58130366 2.15272412 2.27605707 ... 1.68992087 1.36204983 1.09807971]
 ...
 [1.37114427 1.88655819 2.11427157 ... 1.44018665 1.10662381 0.98602345]
 [1.48712266 1.38643424 1.40287356 ... 1.3705948  1.62732467 0.51904526]
 [2.41129195 2.71912426 2.96758433 ... 2.62117497 2.31409005 1.35757232]]


/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


The Original Matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

The Approximation matrix by MF
[[0.40925971 0.22548503 0.0591031  ... 0.32943765 0.28144137 0.36759473]
 [1.16879957 1.01886582 0.33068396 ... 1.00549073 0.5774399  1.03520879]
 [1.21151993 0.88590136 0.30225539 ... 1.14687976 0.71341121 1.09085563]
 ...
 [1.21797234 0.84165576 0.24575409 ... 1.00218044 0.73160453 1.08348572]
 [2.13619523 1.4562597  0.38787921 ... 1.8605431  1.23245908 1.80876668]
 [1.40142735 1.05406037 0.2968452  ... 1.25558198 0.74502923 1.17650541]]


In [ ]:
# print NDCG score for 5 fold validation and its average
print("NDCG score : ", score)
print("NDCG average score : ", np.mean(score))

NDCG score :  [0.9759309390384933, 0.9746077361206373, 0.9722639105289763, 0.9681632445226911, 0.9687211633470916]
NDCG average score :  0.9719373987115778


In [ ]:
# get user items dataframe of best data prediction
df_user_items = df_user_items_pred[score.index(max(score))]
df_user_items

movieId    1         2         3       ...    193585    193587    193609
userId                                 ...                              
1        3.933551  3.518170  2.900238  ...  0.993440  2.436087  3.174977
2        2.882871  2.447925  2.008896  ...  0.786668  1.871760  2.314291
3        1.995446  1.555410  1.470720  ...  0.628178  1.418230  1.563909
4        3.078355  2.690658  2.414947  ...  0.918664  2.073177  2.533924
5        2.584809  2.447476  1.689851  ...  0.590908  1.495623  2.169299
...           ...       ...       ...  ...       ...       ...       ...
606      4.939485  4.259701  3.671055  ...  1.347277  3.200714  3.960659
607      3.459668  2.763920  2.330562  ...  0.984765  2.325968  2.712618
608      4.524387  3.681440  2.826386  ...  1.081800  2.803920  3.461195
609      2.956417  2.332618  1.954379  ...  0.796798  1.946822  2.267649
610      5.316525  4.614487  3.815087  ...  1.427351  3.408722  4.291815

[610 rows x 9724 columns]

In [ ]:
# Get top-20 recommendations for all user
def recommendation(df_user_items, dataset_rating, dataset_movies):
    n_recommendations = 20 # set number of recommendations
    n_users = dataset_rating.userId.unique().shape[0] # get all unique users id count

    for i in range(1,n_users+1):
      user_rating_pred = df_user_items.loc[i].sort_values(ascending=False) # get user rating prediction
      user_rated = (dataset_rating[dataset_rating['userId'] == i].merge(dataset_movies, how = 'left', on='movieId').
                      sort_values(['rating'], ascending=False)) # get user rated movie information

      recommendations = (dataset_movies[~dataset_movies['movieId'].isin(user_rated['movieId'])].
            merge(pd.DataFrame(user_rating_pred).reset_index(), how = 'left',
                  on = 'movieId').
            rename(columns = {i: 'Predictions'}).
            sort_values('Predictions', ascending = False).
                          iloc[:n_recommendations, :-1]
                        ) # get 20-top rated movie recommendation for user that hasn't being watched by user

      print("User id = ", i)
      print("Recommended movies: ")
      for j in range(recommendations.shape[0]):
        print(j+1,".", recommendations['title'].values[j])
      print("\n")

recommendation(df_user_items, dataset_rating, dataset_movies)

Streaming output truncated to the last 5000 lines.
16 . One Flew Over the Cuckoo's Nest (1975)
17 . Death Note: Desu nôto (2006–2007)
18 . Memento (2000)
19 . Game, The (1997)
20 . Amadeus (1984)


User id =  403
Recommended movies: 
1 . Forrest Gump (1994)
2 . Shawshank Redemption, The (1994)
3 . Godfather, The (1972)
4 . Star Wars: Episode IV - A New Hope (1977)
5 . Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
6 . Star Wars: Episode VI - Return of the Jedi (1983)
7 . Fight Club (1999)
8 . Terminator 2: Judgment Day (1991)
9 . Schindler's List (1993)
10 . One Flew Over the Cuckoo's Nest (1975)
11 . Fugitive, The (1993)
12 . Matrix, The (1999)
13 . Star Wars: Episode V - The Empire Strikes Back (1980)
14 . Memento (2000)
15 . Amadeus (1984)
16 . Silence of the Lambs, The (1991)
17 . Dark Knight, The (2008)
18 . Usual Suspects, The (1995)
19 . Inception (2010)
20 . Game, The (1997)


User id =  404
Recommended movies: 
1 . Fight Club (1999)
2 . Goodfell

# **Content Based Filtering (clustering over Movie genre)**

In [ ]:
# get movie dataset
df_movies = dataset_movies
df_movies

movieId  ...                                       genres
0           1  ...  Adventure|Animation|Children|Comedy|Fantasy
1           2  ...                   Adventure|Children|Fantasy
2           3  ...                               Comedy|Romance
3           4  ...                         Comedy|Drama|Romance
4           5  ...                                       Comedy
...       ...  ...                                          ...
9737   193581  ...              Action|Animation|Comedy|Fantasy
9738   193583  ...                     Animation|Comedy|Fantasy
9739   193585  ...                                        Drama
9740   193587  ...                             Action|Animation
9741   193609  ...                                       Comedy

[9742 rows x 3 columns]

In [ ]:
# display all unique genres in movie dataset
movie_genres = df_movies['genres'].str.split("|").to_list()
flatten_list = list(chain.from_iterable(movie_genres)) 
set(flatten_list)

{'(no genres listed)',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'IMAX',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western'}

In [ ]:
# delete movie data where genre is not listed
df_movies = df_movies[df_movies['genres'] != "(no genres listed)"]
df_movies

movieId  ...                                       genres
0           1  ...  Adventure|Animation|Children|Comedy|Fantasy
1           2  ...                   Adventure|Children|Fantasy
2           3  ...                               Comedy|Romance
3           4  ...                         Comedy|Drama|Romance
4           5  ...                                       Comedy
...       ...  ...                                          ...
9737   193581  ...              Action|Animation|Comedy|Fantasy
9738   193583  ...                     Animation|Comedy|Fantasy
9739   193585  ...                                        Drama
9740   193587  ...                             Action|Animation
9741   193609  ...                                       Comedy

[9708 rows x 3 columns]

In [ ]:
# function to count cosine similarity of a specific column towards movie_id

def count_cosine_similarity(column, movies_id):
  # weight keyword tf-idf of column in dataset movies
  tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 1), min_df=0, token_pattern=r"(?u)\w[\w-]*\w")
  tfidf_matrix = tf.fit_transform(column)

  # calculate cosine similarities to find the column values similarity
  cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

  # get dataframe of movie id to column cosine similarities
  recommender_df = pd.DataFrame(cosine_similarities, columns=column, index=movies_id)

  # delete duplicate column (duplicated genres) in dataframe
  recommender_df = recommender_df.loc[:,~recommender_df.columns.duplicated()]
  return recommender_df

recommender_df = count_cosine_similarity(df_movies.genres, df_movies.movieId)
recommender_df

genres   Adventure|Animation|Children|Comedy|Fantasy  ...  Action|Animation|Comedy|Fantasy
movieId                                               ...                                 
1                                           1.000000  ...                         0.680280
2                                           0.813604  ...                         0.341424
3                                           0.152600  ...                         0.181692
4                                           0.135000  ...                         0.160737
5                                           0.267388  ...                         0.318363
...                                              ...  ...                              ...
193581                                      0.680280  ...                         1.000000
193583                                      0.755880  ...                         0.899984
193585                                      0.000000  ...                         0.000000
193587                                      0.421142  ...                         0.753593
193609                                      0.267388  ...                         0.318363

[9708 rows x 950 columns]

In [ ]:
# get one-hot-encoded table of movie genres
df_movie_genre = pd.get_dummies(df_movies['genres'])

# get total of users id in dataframe
n_users = len(df_user_items.index)

# get user-genre similarities dataframe
df_user_genre = pd.DataFrame(columns = recommender_df.columns)
for i in range(1,n_users+1):
    df_user_genre.loc[i] = df_movie_genre.mul(df_user_items.loc[i], axis=0).mean() # multiply one-hot-encoded movie column with user-items dataframe from recommender 1
df_user_genre

genres  Adventure|Animation|Children|Comedy|Fantasy  ...  Action|Animation|Comedy|Fantasy
1                                          0.002034  ...                              0.0
2                                          0.001380  ...                              0.0
3                                          0.000995  ...                              0.0
4                                          0.001648  ...                              0.0
5                                          0.001174  ...                              0.0
..                                              ...  ...                              ...
606                                        0.002546  ...                              0.0
607                                        0.001589  ...                              0.0
608                                        0.001990  ...                              0.0
609                                        0.001352  ...                              0.0
610                                        0.002636  ...                              0.0

[610 rows x 950 columns]

In [ ]:
# initialize user-movie similarity dataframe
df_user_movie_sim_1 = pd.DataFrame(columns = df_user_items.columns)

# get user-movie similarity 
for i in range(1,n_users+1):
  df_user_movie_sim_1.loc[i] = recommender_df.mul(df_user_genre.loc[i]).sum(axis=1)
df_user_movie_sim_1

movieId    1         2         3       ...    193585    193587    193609
1        0.366588  0.220308  0.567280  ...  0.673164  0.202224  0.564695
2        0.255980  0.153657  0.397660  ...  0.472131  0.141388  0.395029
3        0.184786  0.110853  0.287023  ...  0.340811  0.102089  0.285293
4        0.297211  0.178246  0.460973  ...  0.547525  0.164021  0.458873
5        0.217635  0.130637  0.338586  ...  0.402114  0.120189  0.335994
..            ...       ...       ...  ...       ...       ...       ...
606      0.462046  0.277509  0.715733  ...  0.849515  0.254982  0.712254
607      0.300194  0.180191  0.466899  ...  0.554294  0.165925  0.463370
608      0.376999  0.226847  0.584880  ...  0.693579  0.208301  0.580371
609      0.255234  0.153402  0.396235  ...  0.470097  0.141039  0.393367
610      0.483040  0.290027  0.749382  ...  0.889627  0.266670  0.745061

[610 rows x 9724 columns]

In [ ]:
# get user recommendation 
recommendation(df_user_movie_sim_1, dataset_rating, dataset_movies)

Streaming output truncated to the last 5000 lines.
16 . New York Stories (1989)
17 . How to Kill Your Neighbor's Dog (2000)
18 . Avanti! (1972)
19 . The Longest Week (2014)
20 . Masked & Anonymous (2003)


User id =  403
Recommended movies: 
1 . Strike! (a.k.a. All I Wanna Do, The Hairy Bird) (1998)
2 . Parenthood (1989)
3 . Inkwell, The (1994)
4 . Mystery Train (1989)
5 . Lucky You (2007)
6 . I'll Do Anything (1994)
7 . North Dallas Forty (1979)
8 . Network (1976)
9 . Mr. Saturday Night (1992)
10 . Ro.Go.Pa.G. (1963)
11 . Full Monty, The (1997)
12 . Reefer Madness (a.k.a. Tell Your Children) (1938)
13 . Indian Summer (a.k.a. Alive & Kicking) (1996)
14 . Empire Records (1995)
15 . House of Yes, The (1997)
16 . Funny Bones (1995)
17 . Goon (2011)
18 . With Honors (1994)
19 . Jeff, Who Lives at Home (2012)
20 . Kitchen Stories (Salmer fra kjøkkenet) (2003)


User id =  404
Recommended movies: 
1 . Squid and the Whale, The (2005)
2 . Calendar Girl (1993)
3 . Take Me Home Tonight (2011)
4 

# **Content-Based Filtering (Clustering over tags)**

In [ ]:
# get ratings dataset
df_tags = pd.read_csv(drive+'tags.csv', sep=',')
df_tags.head(10)

userId  movieId                tag   timestamp
0       2    60756              funny  1445714994
1       2    60756    Highly quotable  1445714996
2       2    60756       will ferrell  1445714992
3       2    89774       Boxing story  1445715207
4       2    89774                MMA  1445715200
5       2    89774          Tom Hardy  1445715205
6       2   106782              drugs  1445715054
7       2   106782  Leonardo DiCaprio  1445715051
8       2   106782    Martin Scorsese  1445715056
9       7    48516       way too long  1169687325

In [ ]:
# lowercase folding tag column values
df_tags['tag'] = df_tags['tag'].str.lower()

In [ ]:
# get unique values of tag column
x = df_tags['tag'].str.split("|").to_list()
flatten_list = list(chain.from_iterable(x)) 
set(flatten_list)

{'french',
 'scotland',
 'simon pegg',
 'adultery',
 'mafia',
 'beautiful scenery',
 'investor corruption',
 'metaphorical',
 'multiple stories',
 'sisterhood',
 'live action/animation',
 'poor dialogue',
 'philosophical issues',
 'space travel',
 'stand-up comedy',
 'non-linear timeline',
 'trippy',
 'invisibility',
 'ocean',
 'new composer',
 'biopic',
 'witty',
 'tilda swinton',
 'nightclub',
 'depressing',
 'thrilling',
 'prison',
 'lord of the rings',
 'american indians',
 'great humor',
 'whimsical',
 'financial crisis',
 'engrossing adventure',
 'meaningless violence',
 'awkward',
 'ancient rome',
 'trey parker',
 'statue',
 'teachers',
 'philosophy',
 'space epic',
 'may-december romance',
 'cult',
 'psychopaths',
 'british gangster',
 'tolkein',
 'moon',
 'backwards. memory',
 'leonardo dicaprio',
 'race',
 'deep throat',
 'hannibal lecter',
 'long takes',
 'amazing dialogues',
 'monologue',
 'dreamlike',
 'boxing story',
 'ireland',
 'eccentric',
 'nightmare',
 'quentin taran

In [ ]:
# sort tag values by movie id
df_tags = df_tags.sort_values(by=['movieId'])
df_tags

userId  movieId               tag   timestamp
2886     567        1               fun  1525286013
981      474        1             pixar  1137206825
629      336        1             pixar  1139045764
35        62        2    robin williams  1528843907
34        62        2  magic board game  1528843932
...      ...      ...               ...         ...
402       62   187595         star wars  1528934552
528      184   193565            comedy  1537098587
527      184   193565             anime  1537098582
530      184   193565          remaster  1537098592
529      184   193565           gintama  1537098603

[3683 rows x 4 columns]

In [ ]:
# get movie dataset
df_movies = dataset_movies

In [ ]:
# add tag column in movie dataset and set it with empty values
df_movies["tag"] = np.nan
df_movies

movieId  ... tag
0           1  ... NaN
1           2  ... NaN
2           3  ... NaN
3           4  ... NaN
4           5  ... NaN
...       ...  ...  ..
9737   193581  ... NaN
9738   193583  ... NaN
9739   193585  ... NaN
9740   193587  ... NaN
9741   193609  ... NaN

[9742 rows x 4 columns]

In [ ]:
# set value of tag in movie dataset
for index,row in df_tags.iterrows():
  idx = df_movies.index[df_movies["movieId"] == row[1]].tolist()[0]
  if pd.isnull(df_movies["tag"].iloc[idx]):
    df_movies["tag"].iloc[idx] = row[2]
  else:
    if row[2] not in df_movies["tag"].iloc[idx]:
      df_movies["tag"].iloc[idx] += "|"+row[2]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [ ]:
# delete movie rows where tag column value is empty
df_movies = df_movies[~df_movies["tag"].isnull()].iloc[:,[0,1,3]]
df_movies

movieId  ...                                              tag
0           1  ...                                        fun|pixar
1           2  ...          robin williams|magic board game|fantasy
2           3  ...                                        old|moldy
4           5  ...                                 remake|pregnancy
6           7  ...                                           remake
...       ...  ...                                              ...
9681   183611  ...                      comedy|rachel mcadams|funny
9692   184471  ...  adventure|alicia vikander|video game adaptation
9709   187593  ...                josh brolin|ryan reynolds|sarcasm
9710   187595  ...                          emilia clarke|star wars
9732   193565  ...                    comedy|anime|remaster|gintama

[1572 rows x 3 columns]

In [ ]:
# get dataframe of cosine similarity
recommender_df = count_cosine_similarity(df_movies.tag, df_movies.movieId)
recommender_df

tag      fun|pixar  ...  comedy|anime|remaster|gintama
movieId             ...                               
1              1.0  ...                       0.000000
2              0.0  ...                       0.000000
3              0.0  ...                       0.000000
5              0.0  ...                       0.000000
7              0.0  ...                       0.000000
...            ...  ...                            ...
183611         0.0  ...                       0.125494
184471         0.0  ...                       0.000000
187593         0.0  ...                       0.000000
187595         0.0  ...                       0.000000
193565         0.0  ...                       1.000000

[1572 rows x 1024 columns]

In [ ]:
# get total users from user_movie_matrix from recommender 2
n_users = len(df_user_movie_sim_1.index)

In [ ]:
# get one-hot-encoded movie tag
df_movie_tag = pd.get_dummies(df_movies['tag'])

# get user similarity values to all tag
df_user_tag = pd.DataFrame(columns = recommender_df.columns)
for i in range(1,n_users+1):
    df_user_tag.loc[i] = df_movie_tag.mul(df_user_movie_sim_1.loc[i], axis=0).mean() # multiply one-hot-encoded movie tag with user_movie_matrix from recommender 2
df_user_tag

tag  fun|pixar  ...  comedy|anime|remaster|gintama
1          0.0  ...                            0.0
2          0.0  ...                            0.0
3          0.0  ...                            0.0
4          0.0  ...                            0.0
5          0.0  ...                            0.0
..         ...  ...                            ...
606        0.0  ...                            0.0
607        0.0  ...                            0.0
608        0.0  ...                            0.0
609        0.0  ...                            0.0
610        0.0  ...                            0.0

[610 rows x 1024 columns]

In [ ]:
# initialize new user-movie similarity dataframe
df_user_movie_sim_2 = pd.DataFrame(columns = df_user_items.columns)

# map user-movie similarity to dataframe
for i in range(1,n_users+1):
  df_user_movie_sim_2.loc[i] = recommender_df.mul(df_user_tag.loc[i]).sum(axis=1)

df_user_movie_sim_2

movieId    1         2         3       4       ...  193583  193585  193587  193609
1        0.000936  0.001099  0.000218     NaN  ...     NaN     NaN     NaN     NaN
2        0.000656  0.000770  0.000152     NaN  ...     NaN     NaN     NaN     NaN
3        0.000474  0.000556  0.000110     NaN  ...     NaN     NaN     NaN     NaN
4        0.000761  0.000893  0.000177     NaN  ...     NaN     NaN     NaN     NaN
5        0.000559  0.000655  0.000129     NaN  ...     NaN     NaN     NaN     NaN
..            ...       ...       ...     ...  ...     ...     ...     ...     ...
606      0.001181  0.001386  0.000275     NaN  ...     NaN     NaN     NaN     NaN
607      0.000770  0.000904  0.000179     NaN  ...     NaN     NaN     NaN     NaN
608      0.000965  0.001132  0.000225     NaN  ...     NaN     NaN     NaN     NaN
609      0.000654  0.000767  0.000152     NaN  ...     NaN     NaN     NaN     NaN
610      0.001237  0.001451  0.000287     NaN  ...     NaN     NaN     NaN     NaN

[610 rows x 9724 columns]

In [ ]:
# convert all nan values with 0
df_user_movie_sim_2 = df_user_movie_sim_2.fillna(0)
df_user_movie_sim_2

movieId    1         2         3       4       ...  193583  193585  193587  193609
1        0.000936  0.001099  0.000218     0.0  ...     0.0     0.0     0.0     0.0
2        0.000656  0.000770  0.000152     0.0  ...     0.0     0.0     0.0     0.0
3        0.000474  0.000556  0.000110     0.0  ...     0.0     0.0     0.0     0.0
4        0.000761  0.000893  0.000177     0.0  ...     0.0     0.0     0.0     0.0
5        0.000559  0.000655  0.000129     0.0  ...     0.0     0.0     0.0     0.0
..            ...       ...       ...     ...  ...     ...     ...     ...     ...
606      0.001181  0.001386  0.000275     0.0  ...     0.0     0.0     0.0     0.0
607      0.000770  0.000904  0.000179     0.0  ...     0.0     0.0     0.0     0.0
608      0.000965  0.001132  0.000225     0.0  ...     0.0     0.0     0.0     0.0
609      0.000654  0.000767  0.000152     0.0  ...     0.0     0.0     0.0     0.0
610      0.001237  0.001451  0.000287     0.0  ...     0.0     0.0     0.0     0.0

[610 rows x 9724 columns]

In [ ]:
# get top-20 recommended movies for every user
recommendation(df_user_movie_sim_2, dataset_rating, dataset_movies)

Streaming output truncated to the last 5000 lines.
16 . My Left Foot (1989)
17 . Buena Vista Social Club (1999)
18 . Little Voice (1998)
19 . Frankenstein (1931)
20 . Purple Rose of Cairo, The (1985)


User id =  403
Recommended movies: 
1 . Himalaya (Himalaya - l'enfance d'un chef) (1999)
2 . Battle of Algiers, The (La battaglia di Algeri) (1966)
3 . Letter to Three Wives, A (1949)
4 . Letter, The (1940)
5 . Alive (1993)
6 . My Family (1995)
7 . River's Edge (1986)
8 . Terrorist, The (a.k.a. Malli) (Theeviravaathi) (1998)
9 . Rainmaker, The (1997)
10 . That's Entertainment (1974)
11 . Gentlemen Prefer Blondes (1953)
12 . Faust (1926)
13 . Alice Doesn't Live Here Anymore (1974)
14 . Brassed Off (1996)
15 . Our Hospitality (1923)
16 . Tokyo Godfathers (2003)
17 . Cold Comfort Farm (1995)
18 . Dresser, The (1983)
19 . Lone Star (1996)
20 . Black Robe (1991)


User id =  404
Recommended movies: 
1 . How to Steal a Million (1966)
2 . Limelight (1952)
3 . Pride & Prejudice (2005)
4 . Midnig